name: clang-format

on:
  pull_request:
    branches: [ "main" ]
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Normalize line endings
        run: |
          git add --renormalize .

      - name: Run clang-format
        run: |
          clang-format -i $(git ls-files '*.cpp' '*.hpp' '*.h' '*.c')

      - name: Commit and push changes
        run: |
          if ! git diff --quiet; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git commit -am "Normalize line endings and apply clang-format"
            git push
          fi
